import type { Metadata } from "next";
import "./globals.css";
import { NavBar } from "@/components/layout/NavBar";
import { recoleta } from "@/lib/fonts";
import { cn } from "@/lib/cn";
import { Footer } from "@/components/layout/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "max-w-[100vw] md:max-w-full h-min-screen bg-neutral-900 text-white",
          recoleta.className
        )}
      >
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
